# GitHub Actions workflow for remote uploads
name: Remote Upload to Google Drive

on:
  repository_dispatch:
    types: [remote-upload]
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Upload to Google Drive
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.DRIVE_REFRESH_TOKEN_MAIN }}
          PARENT_FOLDER: ${{ secrets.DRIVE_PARENT_FOLDER_MAIN }}
        run: |
          node scripts/upload.js \
            --url "${{ github.event.client_payload.url }}" \
            --filename "${{ github.event.client_payload.filename }}" \
            --correlation-id "${{ github.event.client_payload.correlation_id }}"

      - name: Upload result artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: upload-result
          path: ./result.json
          retention-days: 1
