name: Remote Upload to Google Drive

on:
  repository_dispatch:
    types: [remote-upload]

jobs:
  upload:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Upload to Google Drive
        env:
          # Extension sends these in client_payload
          URL: ${{ github.event.client_payload.url }}
          FILENAME: ${{ github.event.client_payload.filename }}
          REFRESH_TOKEN: ${{ secrets[github.event.client_payload.accountKey] }}
          PARENT_FOLDER: ${{ github.event.client_payload.parentFolderId || secrets[github.event.client_payload.parentKey] }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        run: |
          echo "Starting upload..."
          echo "URL: $URL"
          echo "Filename: $FILENAME"
          echo "Target folder: $PARENT_FOLDER"
          
          # Run upload script (it downloads and uploads in one step)
          node scripts/upload.js --url "$URL" --filename "$FILENAME"
          
          echo "Upload completed!"

      - name: Upload result artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: out/result.json
          retention-days: 1
